name: Publish SK Uplink - Connector

on:
    push:
        tags:
            - "v*"

permissions:
    id-token: write
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org"

            - name: Update npm
              run: npm install -g npm@latest
              working-directory: connector
            - run: npm ci
              working-directory: connector
            - run: npm run build --if-present
              working-directory: connector
            - run: npm publish
              working-directory: connector
